type Query {
  getUsers: [User]!
  getUser(email: String!): User
  usersDepartment(department: String!): [User]!
  countUsersDepartment(department: String!): Int
}
type Mutation {
  createUser(data: inputUser!): User!
  updateUser(id: ID!, data: updateUser!): User!
}
