type Rack {
  _id: ID
  cageId: ID
  codigo: String
  rackType: type
  rackUnits: Int
  Brand: String
  createdAt: String
}

enum type {
  NETWORK
  SERVER
}

input inputRack {
  cageId: ID!
  codigo: String!
  rackType: type!
  rackUnits: Int!
  Brand: String!
}

input updateRack {
  cageId: ID
  codigo: String
  rackType: type
  rackUnits: Int
  Brand: String
}
