type User {
  _id: ID
  fullName: String
  email: String
  role: String
  department: String
  createAt: String # Prepare a directive to format that date value
}

input inputUser {
  fname: String!
  lname: String!
  password: String!
  email: String!
  role: String!
  department: String!
}

input updateUser {
  fname: String
  lname: String
  role: String
  department: String
}
